import {picture, button, textLink, quote, callout} from './components.mjs';

export const meta = {key:'home', path:'/', title:'At Your Service | Mobile Bartending in RI, MA & Eastern CT', description:'Personalized mobile bartending for weddings, private parties, and corporate events in Rhode Island, Massachusetts, and eastern Connecticut. Meet AYS.'};
export function render({site, images, reviews}) {
  return `<section class="hero container"><div class="hero-copy"><p class="eyebrow"><span class="small-line"></span> A LITTLE SPIRIT. A LOT OF HEART.</p><h1>You make<br> the memories.<br><em>We’ll pour<br> the drinks.</em></h1><p class="hero-description">Personalized mobile bartending, thoughtful details, and a warm welcome for every guest. You celebrate. We’re at your service.</p><div class="hero-actions">${button('Let’s plan your event')}${textLink('Explore our services','/services.html')}</div><p class="hero-footnote">WEDDINGS <span>·</span> PRIVATE PARTIES <span>·</span> CORPORATE EVENTS</p></div><div class="hero-visual">${picture(images,'gina',{className:'hero-photo',eager:true,sizes:'(max-width: 760px) 94vw, 48vw'})}<div class="photo-note"><span class="note-star" aria-hidden="true">✧</span><span>A personal touch.<br><em>Every single pour.</em></span></div><span class="image-caption">REAL MOMENTS. BEAUTIFULLY SERVED.</span></div></section>
  <div class="area-strip"><div class="container"><span class="eyebrow">PROUDLY SERVING</span><p>Rhode Island <span aria-hidden="true">✧</span> Massachusetts <span aria-hidden="true">✧</span> Eastern Connecticut</p></div></div>
  <section class="section container"><div class="section-heading"><div><p class="eyebrow">THE OCCASION IS YOURS</p><h2>We’ll bring <em>the hospitality.</em></h2></div><p>From an intimate “I do” to a party with the whole team, we’ll help make the bar feel like part of your celebration.</p></div><div class="event-grid">
  <a class="event-card" href="/services.html#weddings">${picture(images,'couple',{sizes:'(max-width: 650px) 90vw, 30vw'})}<span class="event-number">01 /</span><h3>Weddings <span aria-hidden="true">↗</span></h3><p>A toast to your next chapter.</p></a>
  <a class="event-card" href="/services.html#private-parties">${picture(images,'boat',{sizes:'(max-width: 650px) 90vw, 30vw'})}<span class="event-number">02 /</span><h3>Private parties <span aria-hidden="true">↗</span></h3><p>Big milestones. Just-because moments.</p></a>
  <a class="event-card" href="/services.html#corporate-events">${picture(images,'bar',{sizes:'(max-width: 650px) 90vw, 30vw'})}<span class="event-number">03 /</span><h3>Corporate & more <span aria-hidden="true">↗</span></h3><p>Good company, beyond the office.</p></a></div><p class="section-note">Birthdays, anniversaries, organization functions, boat dock parties, and more. <a href="/services.html#nonprofits">Nonprofit discount rates available.</a></p></section>
  <section class="story-section"><div class="container story-grid"><div class="story-images">${picture(images,'christian',{className:'story-main'})}${picture(images,'menu',{className:'story-detail',sizes:'(max-width: 760px) 40vw, 20vw'})}</div><div class="story-copy"><p class="eyebrow">THE PEOPLE BEHIND THE POUR</p><h2>A little less planning.<br><em>A lot more celebrating.</em></h2><p>We’re Christian and Gina, the duo behind At Your Service Mobile Bartending. To us, you’re more than a client. We want you to feel like family.</p><p>With more than 25 years of combined service industry experience, we take care of the details so you can relax and be fully present for your celebration.</p>${textLink('Get to know us','/about-us.html')}<div class="certification-line"><span aria-hidden="true">✓</span> TIPS-certified bartenders. Thoughtful service.</div></div></div></section>
  <section class="section container service-preview"><div><p class="eyebrow">ALL THE LITTLE DETAILS</p><h2>Your bar.<br> <em>Your way.</em></h2></div><div><p>From a customized drink menu to themed bar décor, we help bring your vision together. We supply the bar essentials and coordinate the drinks, ice, glassware, and garnishes with you.</p>${textLink('See what’s included','/services.html#included')}</div></section>
  <section class="reviews-section"><div class="container"><div class="section-heading"><div><p class="eyebrow">KIND WORDS, GREAT MEMORIES</p><h2>The best part? <em>Happy guests.</em></h2></div>${textLink('More client feedback','/feedback.html')}</div><div class="review-grid">${reviews.filter(r=>r.page==='home').map(r=>quote(r,{compact:true})).join('')}</div></div></section>${callout()}`;
}
